platform :ios, '9.0'

use_frameworks!
install! 'cocoapods', :deterministic_uuids => false

source 'git@github.com:applicaster/CocoaPods.git'
source 'git@github.com:applicaster/CocoaPods-Private.git'
source 'git@github.com:CocoaPods/Specs.git'

target 'ZappPlayerPluginYoutube_Example' do
  pod 'ZappPlayerPluginYoutube', :path => '../ZappPlayerPluginYoutube.podspec'

  target 'ZappPlayerPluginYoutube_Tests' do
    inherit! :search_paths


  end
end
